// clear
export const CLEAR_STORE = 'CLEAR_STORE';

// stores
export const GET_STORES = 'GET_STORES';

// food waste
export const GET_FOOD_WASTE_ZIP = 'GET_FOOD_WASTE_ZIP';
export const GET_FOOD_WASTE_ID = 'GET_FOOD_WASTE_ID';

// suggestions
export const GET_RELEVANT_PRODUCTS = 'GET_RELEVANT_PRODUCTS';
export const GET_SIMILAR_PRODUCTS = 'GET_SIMILAR_PRODUCTS';
export const GET_FREQUENTLY_BOUGHT_TOGEHTER = 'GET_FREQUENTLY_BOUGHT_TOGEHTER';
